apiVersion: 1
datasources:
  - name: CBM-InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: abadan
      defaultBucket: cbm_timeseries
    secureJsonData:
      token: dev-influx-token
    isDefault: true
